name: Rush 01 testing

on:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    steps:
    - name: Install
      run: apt install haskell-platform
      run: curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

    - name: Compiling
      run: make

    - name: Test KO 01
      run: echo "sa pb pb pb" | ./pushswap_checker 2 1 3 6 5 8

    - name: Test OK 02
      run: echo "sa pb pb pb sa pa pa pa" | ./pushswap_checker 2 1 3 6 5 8

    - name: Test SWAP 03
      run: echo "sa" | ./pushswap_checker 2 1

    - name: Test NEGATIVE SWAP 04
      run: echo "sa" | ./pushswap_checker 1 -4

    - name: Test RA 05
      run: echo "ra" | ./pushswap_checker 4 1 3
